application: running-with-zebras-101
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  script: stylesheets

- url: /.*
  script: guestbook.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
